runtime: python39
entrypoint: gunicorn -b :$PORT run:app

# Optional settings:
handlers:
- url: /.*
  script: auto

env_variables:
  NLTK_DATA: "/tmp/nltk_data"
  MONGODB_URI: 'mongodb+srv://mike:Password123%21@labassistant.xvoen.mongodb.net/?retryWrites=true&w=majority&appName=labassistant'
  MONGODB_DB: 'lab'